### ISSUE TITLE
Buscador

### ISSUE THREAD

**Issue by Gio-mustard** [RyanAg06/MyStuff#12]
Seria una buena idea crear un buscador que funcione de la siguiente manera.

1. Busca a partir de los elementos (tarjetas) que estan ya declarados en el html
2. Muestra una ventana emergente con los resultados de la búsqueda (esto para evitar modificar el contenido de la pagina)

Como primer versión podría solo buscar a partir del titulo de la tarjeta.

**Comment by Gio-mustard** [comment]
@RyanAg06 que opinas ?? empiezo a desarrollar ?

**Comment by RyanAg06** [comment]
Me parece bien, ya despues podriamos agregar categorias a las tarjetas y buscar por filtros, si gustas ir comenzando

**Comment by Gio-mustard** [comment]
Okey perfecto, empezare con el desarrollo, iré poniendo los avances o dudas aqui.
