### ISSUE TITLE
modularizacion  de estilos

### ISSUE THREAD

**Issue by Gio-mustard** [RyanAg06/MyStuff#3]
Hay que crear un sub paquetes de estilos para separarlos por...
* Paginas
* Resoluciones (tablet,computadora,telefono)

**Comment by RyanAg06** [comment]
eso ya esta hecho en la parte de css, estan divididas por version de escritorio, tablet y celular

**Comment by Gio-mustard** [comment]
Ah si, no fui especifico perdon, me refiero a separarlo por archivos, para que cuando crezca mas el código no sea tan difícil leerlo, incluso podríamos separar los css de esta forma...
```
-styles
--home
----desktop.css
----mobile.css
--otherPage
----desktop.css
----mobile.css
```

**Comment by RyanAg06** [comment]
No habia visto, me parece bien lo implementare
