### ISSUE TITLE
revisión de cerrar y abrir sub menús

### ISSUE THREAD

**Issue by Gio-mustard** [RyanAg06/MyStuff#7]
Los algoritmos para abrir y cerrar los sub menús potencialmente podrían estar ejecutando código redundante y podríamos corregir esto para optimizar un poco mas su funcionamiento.

# Explicación
En el script funciones.js en el evento resize de la ventana se ejecutan 2 funciones. 
```js
window.addEventListener("resize", ()=>
{
    abrirSubMenus();
    cerrarSubmenus();
});
```
estas funciones en conjunto iteran 3 veces en los elementos del menú de navegación y les agregan eventos para abrir o cerrar sub menús.

## problematica
El problema es que si el código ya se ejecuto una vez no hay necesidad de hacerlo 2 veces, incluso esto podría ejecutarse decenas de veces mientras se hace un resize a la ventana, esto hará que se ejecute código innecesario .

## posible solución
Se podría usar una variable global que funcione como verificador para saber si ya se ejecuto o no el algoritmo.

**Comment by RyanAg06** [comment]
esto lo hice ya que al momento de cambiar el tamaño de la ventana los submenus se quedaban abiertos y cuamdo pasabas a modo escritorio todo se quedaba visible, pero puedo verificarlo de nuevo;)

**Comment by Gio-mustard** [comment]
Podríamos separar las funciones para que los eventos se asignen una vez y que haga la verificación de la resolución siempre para saber si debe o no cerrar el menú lateral.

**Comment by Gio-mustard** [comment]
Oyeee, recuerda hacer la referencia del commit cuando cierres un issue para poder leer el codigo, tambien puedes poner un comentario aqui con el ID del commit para tener el seguimiento mas facil
