### ISSUE TITLE
Crear Slider de Imagenes Dinamico

### ISSUE THREAD

**Issue by RyanAg06** [RyanAg06/MyStuff#8]
Crear un slider dinamico que no importa la cantidad de imagenes, este va seguir funcionando igual y que sea manual usando botones para avanzar y retroceder de imagenes.

**Comment by Gio-mustard** [comment]
este slider tiene que redireccionar a otra seccion del sitio??

**Comment by RyanAg06** [comment]
> este slider tiene que redireccionar a otra seccion del sitio??

Nop, solo mover las imagenes

**Comment by Gio-mustard** [comment]
Entonces Cual es el objetivo del slider de imagenes??

**Comment by RyanAg06** [comment]
> Entonces Cual es el objetivo del slider de imagenes??

Enseñar Las Imagenes de Como va Quedando o Simplemente los Pasos

**Comment by Gio-mustard** [comment]
Deberías hacer un boceto de diseno y ponerlo aqui para cuando este listo lo implemente en una pagina para que hagamos pruebas (ya casi funciona por cierto)

**Comment by RyanAg06** [comment]
> Deberías hacer un boceto de diseno y ponerlo aqui para cuando este listo lo implemente en una pagina para que hagamos pruebas (ya casi funciona por cierto)

Me dices cuando este listo, ya te pase unas pruebas
