### ISSUE TITLE
Documentar Codigo: HTML, CSS y JS

### ISSUE THREAD

**Issue by RyanAg06** [RyanAg06/MyStuff#9]
Comentar el codigo de HTML; documentar que hace cada etiqueta, con CSS documentar cada estilo que se agrega y para JS documentar que hace cada cosa exactamente.

**Comment by Gio-mustard** [comment]
Podriamos hacer un archivo de "guia" que sea .md para tener estructurado que hace cada cosa, podria yo crear la estructura y tu la documentación ya que tienes mas experiencia con eso ya que tu creaste casi todo. @RyanAg01

**Comment by RyanAg06** [comment]
Me parece bien, y ahi meto como implementar cada elemento y demas

**Comment by Gio-mustard** [comment]
Bien, creo el archivo y lo subo a la rama Completa ??

**Comment by RyanAg06** [comment]
> Bien, creo el archivo y lo subo a la rama Completa ?? 

Sip

**Comment by Gio-mustard** [comment]
@RyanAg01 porfa haz la referencia a los commits cuando cierres un issue x-x me facilita mas el leer el código que cambiaste. Gracias:]

**Comment by RyanAg06** [comment]
> @RyanAg01 porfa haz la referencia a los commits cuando cierres un issue x-x me facilita mas el leer el código que cambiaste. Gracias:]

Sisi mano
